src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
use ConsoleTVs\Profanity\Builder;
use ConsoleTVs\Profanity\Facades\Profanity;
/*use Sb\Bundle\StarRatingBundle\Model\RateableInterface;
use Sb\Bundle\StarRatingBundle\Model\RateableTrait;*/



#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("reclamations")]
    private ?int $id = null;

    

    /*#[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Ce champ est obligatoire')]
    */
    #[ORM\Column(length: 255)]
    #[Groups("reclamations")]
    #[Assert\NotBlank(message:"Nom is required")]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Groups("reclamations")]
    #[Assert\NotBlank(message:"Prenom is required")]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    #[Groups("reclamations")]
    #[Assert\NotBlank(message:"Email is required")]
    #[Assert\Email(message:"the email '{{ value }}' is not a valid email")]
    private ?string $email = null;

   #[ORM\Column(type: Types::TEXT)]
   #[Groups("reclamations")]
    #[Assert\NotBlank(message:"Description is required")]
    private ?string $description  = null ;
    
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups("reclamations")]
   // #[Assert\NotBlank(message: 'Ce champ est obligatoire')]

    public ?\DateTimeInterface $date_rec = null;



    #[ORM\Column(length: 255)]    
    #[Groups("reclamations")]
    #[Assert\NotBlank(message: 'Ce champ est obligatoire')]

    private ?int $type_rec = null;

    /**
     * @ORM\OneToMany(targetEntity="Reponse", mappedBy="reclamation")
     */
    private $reponses;

    public function __construct()
    {
        $this->reponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function construct()
    {
        $this->date_rec = new \DateTime();
    }


        

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    
    {   
        $clean_words = \ConsoleTVs\Profanity\Builder::blocker($description)->filter();
        $this->description = $clean_words;

        /*$this->description = $description;*/

        return $this;
    }
    
    public function getDateRec(): ?\DateTimeInterface
    {
        return $this->date_rec;
    }

    public function setDateRec(?\DateTimeInterface $date_rec): self
    {
        $this->date_rec = $date_rec;

        return $this;
    }

    public function getTypeRec(): ?int
    {
        return $this->type_rec;
    }

    public function setTypeRec(?int $type_rec): self
    {
        $this->type_rec = $type_rec;

        return $this;
    }
    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    public function __toString()
    {
        return (string)$this->getId();
    }

    /**
     * @return Collection<int, Reponse>
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponse $reponse): self
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses->add($reponse);
            $reponse->setReponses($this);
        }

        return $this;
    }

    public function removeReponse(Reponse $reponse): self
    {
        if ($this->reponses->removeElement($reponse)) {
            // set the owning side to null (unless already changed)
            if ($reponse->getReponses() === $this) {
                $reponse->setReponses(null);
            }
        }

        return $this;
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',null,['label' => 'Recherche par Nom ',
            'attr' => ['requied' => false, 
                       'placeholder' => 'Entrer le nom du client '] ] ) 
            ->add('prenom')
            ->add('email')
            ->add('description')
            //->add('date_rec')
          //  ->add('type_rec')
          ->add('type_rec',ChoiceType::class,['choices'=> [
           // ''=>'',
            'Normale'=>'1',
            'Administrative'=>'2',
            
        ],])

        ;
    }

    

    
      
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Service\BadWordsFilter;
use App\Repository\ReclamationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\SerializerInterface;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\Material\BarChart;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use Doctrine\ORM\Query\Expr\Func;
use Doctrine\ORM\Query\Expr;
use Doctrine\ORM\Query\ResultSetMapping;
use Twilio\Rest\Client;







    #[Route('/reclamation')]
class ReclamationController extends AbstractController
{
    #[Route('/', name: 'app_reclamation_index', methods: ['GET'])]
    public function index(ReclamationRepository $ReclamationRepository,Request $request): Response
    {
        $reclamation = new Reclamation();
        $form1 = $this->createForm(ReclamationType::class,$reclamation);
        $form1->handleRequest($request);
       //initialement le tableau des reclamation est vide, 
       //c.a.d on affiche les reclamation que lorsque l'utilisateur clique sur le bouton rechercher
        $reclamation= [];
        
       if($form1->isSubmitted() && $form1->isValid()) {
       //on récupère le nom d'article tapé dans le formulaire
        $nom = $propertySearch->getNom();   
        if ($nom!="") 
          //si on a fourni un nom d'article on affiche tous les reclamation ayant ce nom
          $reclamation= $this->getDoctrine()->getRepository(ReclamationType::class)->findBy(['nom' => $nom] );
        else   
          //si si aucun nom n'est fourni on affiche tous les reclamation
          $reclamation= $this->getDoctrine()->getRepository(ReclamationTypes::class)->findAll();
       }
        return  $this->render('reclamation/index.html.twig',[ 'form1' =>$form1->createView(), 'reclamations' => $ReclamationRepository->findAll()]);  
      
    }
    #[Route('/search', name: 'search_reclamation')]

    public function search(Request $request, ReclamationRepository $repository): Response
    {
       

        $query = $request->query->get('query');
        $reclamation = $repository->findBySearchQuery($query);


        return $this->render('reclamation/index.html.twig', [
            'query' => $query,
            'reclamations' => $reclamation
           
        ]);
    }




    
     /**
     * @Route("/statistic", name="statis")
     */

    
     


        //$ach = $ReclamationRepository->sewy();
       /* $date_rec = '2023-03-09'; // Remplacez ceci par la date à rechercher
        $nbreDatesSimilaires = $ReclamationRepository->sewy($date_rec);
        $total = $ReclamationRepository->count([]);
         $pieChart = new PieChart();
         $pieChart->getData()->setArrayToDataTable(
            // [['reclamation', 'date_rec'],
//['date_rec 1', intVal($ach)],
['Reclamation', 'Nombre'],
['Dates similaires', intval($nbreDatesSimilaires)],
['Autres dates', intval($total - $nbreDatesSimilaires)],

         );
         $pieChart->getOptions()->setTitle('Suiiiiiiiiiii'.$date_rec);
         $pieChart->getOptions()->setHeight(500);
         $pieChart->getOptions()->setWidth(900);
         $pieChart->getOptions()->getTitleTextStyle()->setBold(true);
         $pieChart->getOptions()->getTitleTextStyle()->setColor('#009900');
         $pieChart->getOptions()->getTitleTextStyle()->setItalic(true);
         $pieChart->getOptions()->getTitleTextStyle()->setFontName('Arial');
         $pieChart->getOptions()->getTitleTextStyle()->setFontSize(20);*/
 

    
          
        /*return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamationRepository->findAll(),
        ]);
    }*/
    
    
    /**
     * @Route("/stats", name="stats")
     */
    public function statisreclamation(ReclamationRepository $ReclamationRepository)
{
      //on va chercher les categories
      $rech = $ReclamationRepository->barDep();
      $arr = $ReclamationRepository->barArr();
      
      $bar = new barChart ();
      $bar->getData()->setArrayToDataTable(
          [['Reclamation', 'aaaa
          '],
           ['1', intVal($rech)],
           ['2', intVal($arr)],
          
  
          ]
      );
  
      $bar->getOptions()->setTitle('les Reclamations');
      $bar->getOptions()->getHAxis()->setTitle('Nombre de reclamation');
      $bar->getOptions()->getHAxis()->setMinValue(0);
      $bar->getOptions()->getVAxis()->setTitle('type_rec');
      $bar->getOptions()->SetWidth(800);
      $bar->getOptions()->SetHeight(400);
  
  
      return $this->render('/stats.html.twig', array('bar'=> $bar )); 
    }
       
  
  
    /*public function statistiques(ReclamationRepository $ReclamRepos){
        // On va chercher toutes les catégories
        $reclamation = $ReclamRepos->findAll();

        $ReclamReposNom = [];
        $ReclamReposColor = [];
        $ReclamReposCount = [];

        // On "démonte" les données pour les séparer tel qu'attendu par ChartJS
        foreach($reclamation as $rec){
            $ReclamReposNom[] = $rec->getNom();
            $ReclamReposColor[] = $rec->getCouleur();
            $ReclamReposCount[] = count($rec->getTypeRec());
        }

        return $this->render('/stats.html.twig', [
            'ReclamReposNom' => json_encode($ReclamReposNom),
            'ReclamReposColor' => json_encode($ReclamReposColor),
            'ReclamReposCount' => json_encode($ReclamReposCount), ]); }
/*
         /**
     * @Route("/searchrec", name="search", methods={"GET"})
     */
   /* public function searchrec(Request $request, NormalizerInterface $Normalizer)
    {
        $reclamation=($this->getDoctrine()->getRepository(Reclamation::class)->findBy(['Nom' => $request->get('search')])
            
            

        );
        dump($request->get('search'));
        if (null != $request->get('search')) {
            return $this->render('/reclamation/index.html.twig', [
                'reclamation' => $reclamation,
                

            ]);
        }
    }*/
    
   /*  public function statistiques(ReclamationRepository $reclamationRepository){
       
      $reclamation=$reclamationRepository->findAll();

      $reclamNom = [];
      $reclamPrenom = [];
      $reclamDateRec = [];
       // On "démonte" les données pour les séparer tel qu'attendu par ChartJS
       foreach($reclamation as $rec){
        $reclamNom[] = $rec->getNom();
        $reclamPrenom[] = $rec->getPrenom();
        $reclamTypeRec[] = $rec->getTypeRec();
        $reclamDateRec[] =  $rec->getDateRec();
    }

       
    return $this->render('/stats.html.twig', [
        'reclamNom' => json_encode($reclamNom),
        'reclamPrenom' => json_encode($reclamPrenom),
        'reclamDateRec' => json_encode($reclamDateRec),
        'reclamTypeRec' => json_encode($reclamTypeRec),

        //'recdates' => json_encode($recdates),



    ]);
}*/
        /*$reclamDateRec[] = count($rec->getTypeRec());*/

         // On va chercher le nombre d'annonces publiées par date
        /* $reclamation = $reclamationRepository->countByDate();

         $date_rec = [];
         $RecCount = [];
 
         // On "démonte" les données pour les séparer tel qu'attendu par ChartJS
         foreach($reclamation as $rec){
             $date_rec[] = $reclamation['date_rec'];
             $RecCount[] = $rec['count'];
         }*/
    
   /* #[Route('/search', name: 'app_search')]
    public function search(Request $request)
    {
        return $this->render('search/reclamation.html.twig');
            
    }*/
/*#[Route('/', name: 'app_reclamation_index', methods: ['GET','POST'])]
       public function new(Request $request, BadWordsFilter $badWordsFilter): Response
    {
        $description = new  description();
        $form = $this->createForm(descriptionType::class, $description);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $description->setText($badWordsFilter->filter($description->getText()));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($description);
            $entityManager->flush();
            return $this->redirectToRoute('description_index');
        }

        return $this->render('description/new.html.twig', [
            'description' => $description,
            'form' => $form->createView(),
        ]);
    }
/*

    /*
class CommentController extends AbstractController
{
    /**
     * @Route("/comment/new", name="comment_new", methods={"GET","POST"})
     */
    /*public function new(Request $request, BadWordsFilter $badWordsFilter): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setText($badWordsFilter->filter($comment->getText()));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('comment_index');
        }

        return $this->render('comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }
}
/*
    #[Route('/', name: 'app_reclamation_index', methods: ['GET','POST'])]
    public function index(ReclamationRepository $reclamationRepository,Request $request): Response
    {
$propertySearch = new PropertySearch();

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/reclamation/_form.html.twig
{{form_start(form,{'attr':{'novalidate': 'novalidate'}} )}}
<table>
<tr>
<td> {{ form_label(form.nom,"Nom")  }}
 </td>
<td>  {{ form_widget(form.nom) }}
</td>  
<td> {{ form_errors(form.nom) }}
</td>
</tr>

<tr>
<td> {{ form_label(form.prenom,"Prenom")  }}
 </td>
<td>  {{ form_widget(form.prenom) }}
</td>  
<td> {{ form_errors(form.prenom) }}
</td>
</tr>

<td>  {{ form_label(form.email,"Email") }}
</td>
<td> {{ form_widget(form.email)}}
 </td>
<td>  {{ form_errors(form.email) }}
</td>

</tr>
<tr>

<td>  {{ form_label(form.description,"Description") }}
</td>
<td> {{ form_widget(form.description)}}
 </td>
<td>  {{ form_errors(form.description) }}
</td>



<tr>

<td>  {{ form_label(form.type_rec,"type") }}
</td>
<td> {{ form_widget(form.type_rec)}}
 </td>
<td>  {{ form_errors(form.type_rec) }}
</td>

</tr>

</table>
<br>
<br>
    <button class="btn btn-success rounded-pill">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reclamation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reclamation{% endblock %}

{% block body %}
<br><br>
<center>
    <h1>Edit Reclamation</h1>

    {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}
    <br>
    
        {{ include('reclamation/_delete_form.html.twig') }}
    <br>
    </center>

    <a href="{{ path('app_reclamation_index') }}"class="previous">&laquo;back to list</a>


{% endblock %}

templates/reclamation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vos Reclamations
{% endblock %}

{% block body %}
    <h1>Vos Reclamations</h1>
     <div class="col-lg-4" style="float: left">
                <div class="card my-4">
                    <h5 class="card-header">Rechercher</h5>
                    <div class="card-body">
                        <div class="input-group" >
                            <form method="get" action="{{ path('search_reclamation') }}">
                                <input type="text" name="query" class="search-input" placeholder="Rechercher publication">

                                <style>
								

                                    .search-input {
                                        border: 1px solid #ccc;
                                        border-radius: 5px;
                                        box-sizing: border-box;
                                        font-size: 16px;
                                        padding: 10px;
                                        width: 100%;
                                    }

                                    .search-input::placeholder {
                                        color: #aaa;
                                    }
                                </style>

                                <button type="submit" class="search-button">Rechercher</button>

                                <style>
                                    .search-button {
                                        background: linear-gradient(to bottom, #6c757d, #5a6268);
                                        border-radius: 5px;
                                        border: none;
                                        color: #fff;
                                        cursor: pointer;
                                        font-size: 16px;
                                        font-weight: bold;
                                        padding: 10px 20px;
                                        text-align: center;
                                        text-decoration: none;
                                        transition: all 0.2s ease-in-out;
                                    }

                                    .search-button:hover {
                                        background: linear-gradient(to bottom, #5a6268, #6c757d);
                                    }
                                </style>
                            </form>
              </span>
                        </div>
                    </div>
                </div>


            </div>
   {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
        {% endfor %}



    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                
                
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Description</th>
            
                <th>Date reclamation</th>
                <th>Type reclamation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
       
        {% for reclamation in reclamations %}
            <tr>
                <td>{{ reclamation.id }}</td>
                <td>{{ reclamation.nom }}</td>
                <td>{{ reclamation.prenom }}</td>
                <td>{{ reclamation.email }}</td>
                
                <td>{{ reclamation.description }}</td>
                <td>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d') : '' }}</td>
                <td>{{ reclamation.typeRec }}</td>
                <td>
                    <a class="btn btn-secondary" href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">show</a>
                    
                    <td><a class="btn btn-success"href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>
                     </td>
                <td>    {{ include('reclamation/_delete_form.html.twig') }}
                 </td>             
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a  href="{{ path('app_reclamation_index') }}" class="previous">&laquo;back to list</a>

   <a class=' btn btn-primary rounded-pill' href="{{ path('app_reclamation_new') }}">Create new</a>

{% endblock %}

templates/reclamation/new.html.twig
{% extends 'base.html.twig' %}



{% block body %}

<br><br>
<center>
<h1> Reclamation </h1>

{{include('reclamation/_form.html.twig')}}
 </center> 

<a href="{{ path('app_reclamation_index') }}" class="previous">&laquo; back to list</a>
 

{% endblock body %}

templates/reclamation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block body %}


    <h1>Reclamation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
           <tr>
                <th>Nom</th>
                <td>{{ reclamation.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ reclamation.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ reclamation.email }}</td>
            </tr>
            <tr>
                <th>Deseditiption</th>
                <td>{{ reclamation.description }}</td>
            </tr>
            <tr>
                <th>Date Reclamation</th>
                <td>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Type Reclamation</th>
                <td>{{ reclamation.typeRec }}</td>
            </tr>
        </tbody>
    </table>
<center>
 <a class="btn btn-success"href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>
<br>
<br>
    {{ include('reclamation/_delete_form.html.twig') }}
    <br>


</center>
    <a  href="{{ path('app_reclamation_index') }}" class="previous">&laquo;back to list</a>




{% endblock %}