src/Entity/Accident.php
<?php

namespace App\Entity;

use App\Repository\AccidentRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\DomCrawler\Image;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Length;



#[ORM\Entity(repositoryClass: AccidentRepository::class)]
class Accident
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("accident")]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "matricule ne doit pas etre vide")]
    #[Groups("accident")]
    private ?string $nom_client = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "matricule ne doit pas etre vide")]
    #[Groups("accident")]

    private ?string $prenom_client = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "matricule ne doit pas etre vide")]
    #[Length( min: 5,minMessage: "entrer une matricule au minimum de 5 chiffres")]
    #[Groups("accident")]

    private ?string $matricule = null;

    #[ORM\Column(type: "string", length: 255, nullable: true,)]
    #[Assert\NotBlank(message: "matricule ne doit pas etre vide")]
    #[Groups("accident")]
    private $image;


    #[ORM\Column(type: "string", length: 255, nullable: true,)]
    #[Assert\NotBlank(message: "matricule ne doit pas etre vide")]
    #[Groups("accident")]
    private $image_voiture_reparee;


    #[ORM\Column(type: "string", length: 255, nullable: true)]
    #[Assert\NotBlank(message: "matricule ne doit pas etre vide")]
    #[Groups("accident")]
    private $image_piece_endommage;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    #[Assert\NotBlank(message: "matricule ne doit pas etre vide")]
    #[Groups("accident")]
    private $image_nouveau_pieces;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    #[Assert\NotBlank(message: "matricule ne doit pas etre vide")]
    #[Groups("accident")]
    private $image_facture_reparation;

    #[ORM\ManyToOne(targetEntity: Project::class, inversedBy: 'accidents')]
    #[ORM\JoinColumn(nullable: false)]
    private  $lieu_mecaniciens = null;




    public function getImage()
    {
        return $this->image;
    }


    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function addImage(Image $image): void
    {

        if (!$this->image->contrains($image)) {
            $this->image[] = $image;
            $image->setAccident($this);
        }
    }


    public function getNomClient(): ?string
    {
        return $this->nom_client;
    }

    public function setNomClient(string $nom_client): self
    {
        $this->nom_client = $nom_client;

        return $this;
    }

    public function getPrenomClient(): ?string
    {
        return $this->prenom_client;
    }

    public function setPrenomClient(string $prenom_client): self
    {
        $this->prenom_client = $prenom_client;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }


    public function getImageVoitureReparee()
    {
        return $this->image_voiture_reparee;
    }


    public function setImageVoitureReparee($image_voiture_reparee): void
    {
        $this->image_voiture_reparee = $image_voiture_reparee;
    }


    public function getImagePieceEndommage()
    {
        return $this->image_piece_endommage;
    }


    public function setImagePieceEndommage($image_piece_endommage): void
    {
        $this->image_piece_endommage = $image_piece_endommage;
    }


    public function getImageNouveauPieces()
    {
        return $this->image_nouveau_pieces;
    }

    public function setImageNouveauPieces($image_nouveau_pieces): void
    {
        $this->image_nouveau_pieces = $image_nouveau_pieces;
    }

    public function getImageFactureReparation()
    {
        return $this->image_facture_reparation;
    }


    public function setImageFactureReparation($image_facture_reparation): void
    {
        $this->image_facture_reparation = $image_facture_reparation;
    }

    public function getLieumecaniciens(): ?Project
    {
        return $this->lieu_mecaniciens;
    }

    public function setLieumecaniciens(?Project $lieu_mecaniciens): self
    {
        $this->lieu_mecaniciens = $lieu_mecaniciens;

        return $this;
    }






}

src/Form/AccidentType.php
<?php

namespace App\Form;

use App\Entity\Accident;
use App\Entity\Project;
use Karser\Recaptcha3Bundle\Form\Recaptcha3Type;
use Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3;
use phpDocumentor\Reflection\Types\False_;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class AccidentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('nom_client')
            ->add('prenom_client')
            ->add('matricule')
            ->add('lieu_mecaniciens',EntityType::class,
                ['class'=>Project::class,
                    'choice_label'=>'lieu_garage','multiple'=>false,'required'=>false,])


            ->add('image',FileType::class,[
              'label' => 'image voiture' ,
                'mapped' => true,
                'required' => false,
                'multiple' => true,


            ])
            ->add('image_voiture_reparee',FileType::class,[
                'mapped' => true,
                'required' => false,
                'multiple' => true,


            ])
            ->add('image_piece_endommage',FileType::class,[

                'mapped' => true,
                'required' => false,
                'multiple' => true,


            ])
            ->add('image_nouveau_pieces',FileType::class,[

                'mapped' => true,
                'required' => false,
                'multiple' => true,



            ])
            ->add('image_facture_reparation',FileType::class,[
                'mapped' => true,
                'required' => false,
                'multiple' => true,


            ])
            ->add('captcha', Recaptcha3Type::class, [
                'constraints' => new Recaptcha3(),
                'action_name' => 'accident',

            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Accident::class,
        ]);
    }

}

src/Controller/AccidentController.php
<?php

namespace App\Controller;

use App\Entity\Accident;
use App\Entity\Categorie;
use App\Entity\Project;
use App\Form\AccidentType;
use App\Repository\AccidentRepository;
use App\Repository\ArticleRepository;
use App\Repository\ProjectRepository;
use App\Service\PictureService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\String\Slugger\SluggerInterface;
use Swift_Message;
use Swift_Mailer;
#[Route('/accident')]
class AccidentController extends AbstractController
{
    #[Route('/', name: 'app_accident_index', methods: ['GET'])]
    public function index(AccidentRepository $accidentRepository,PaginatorInterface $paginator, Request $request): Response
    {
        $accident = $accidentRepository->findAll();

        $accident = $paginator->paginate(
            $accident, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3 /*limit per page*/
        );


        return $this->render('accident/index.html.twig', ['accidents' => $accident]);
    }
    #[Route('/map',name:'map')]
    public function map(AccidentRepository $repository){

        return $this->render('accident/new.html.twig');

    }
    #[Route('/affiche', name: 'app_accident_index1', methods: ['GET'])]
    public function index2(AccidentRepository $accidentRepository): Response
    {
        return $this->render('base.html.twig', [
            'accidents' => $accidentRepository->findAll(),
        ]);
    }











    #[Route('/new', name: 'app_accident_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AccidentRepository $accidentRepository,SluggerInterface $slugger,Swift_Mailer $mailer): Response
    {

        $accident = new Accident();
        $form = $this->createForm(AccidentType::class, $accident);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {


            //$imageFile = $form->get('image')->getData();



            $uploadedFiles = $form->get('image')->getData();
            $accident->setImage($this->movefiles($slugger,$uploadedFiles,$accident));


            $uploadedFiles = $form->get('image_voiture_reparee')->getData();
            $accident->setImageVoitureReparee($this->movefiles($slugger,$uploadedFiles,$accident));


            $uploadedFiles = $form->get('image_piece_endommage')->getData();
            $accident->setImagePieceEndommage($this->movefiles($slugger,$uploadedFiles,$accident));

            $uploadedFiles = $form->get('image_nouveau_pieces')->getData();
            $accident->setImageNouveauPieces($this->movefiles($slugger,$uploadedFiles,$accident));

            $uploadedFiles = $form->get('image_facture_reparation')->getData();
            $accident->setImageFactureReparation($this->movefiles($slugger,$uploadedFiles,$accident));





           /* if ($imageFile) {
                $originalfilename = pathinfo($accident->getNomClient(), flags: PATHINFO_FILENAME);
                $safefilename = $slugger->slug($originalfilename);
                $newFilename = $safefilename.'-'.uniqid() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('personne_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // gestion de l'erreur
                }

                $accident->setImage($newFilename);

            }
*/






            $accidentRepository->save($accident, true);
            $this->sendEmail($mailer);

            return $this->redirectToRoute('client_front', [], Response::HTTP_SEE_OTHER);
        }
            return $this->renderForm('accident/new.html.twig', [
                'accident' => $accident,
                'form' => $form,
            ]);

    }


    #[Route("/allaccidentsjson", name:"list")]

    public function getaccidentsjson(AccidentRepository $repo, NormalizerInterface $normalizer)
    {

        $accidents = $repo->findAll();

        $accidentsNormalises = $normalizer->normalize($accidents,'json', ['groups' => "accident"]);

        $json = json_encode($accidentsNormalises);

        return new Response($json);
    }




   #[Route("/addaccidentjson/new", name:"list")]

    public function addaccidentjson(Request $req, NormalizerInterface $normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $accidents = new Accident();
        $accidents->setPrenomClient($req->get('prenom_client'));
        $accidents->setNomClient($req->get('nom_client'));
        $accidents->setMatricule($req->get('matricule'));
        $em->persist($accidents);
        $em->flush();

        $jsonContent = $normalizer->normalize($accidents,'json', ['groups' => 'accident']);

        return new Response(json_encode($jsonContent));

    }





    #[Route('/{id}', name: 'app_accident_show', methods: ['GET'])]
    public function show(Accident $accident): Response
    {
        return $this->render('accident/show.html.twig', [
            'accident' => $accident,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_accident_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Accident $accident, AccidentRepository $accidentRepository,SluggerInterface $slugger): Response
    {
        $form = $this->createForm(AccidentType::class, $accident);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $uploadedFiles = $form->get('image')->getData();
            $accident->setImage($this->movefiles($slugger,$uploadedFiles,$accident));


            $uploadedFiles = $form->get('image_voiture_reparee')->getData();
            $accident->setImageVoitureReparee($this->movefiles($slugger,$uploadedFiles,$accident));



            $uploadedFiles = $form->get('image_piece_endommage')->getData();
            $accident->setImagePieceEndommage($this->movefiles($slugger,$uploadedFiles,$accident));



            $uploadedFiles = $form->get('image_nouveau_pieces')->getData();
            $accident->setImageNouveauPieces($this->movefiles($slugger,$uploadedFiles,$accident));

            $uploadedFiles = $form->get('image_facture_reparation')->getData();
            $accident->setImageFactureReparation($this->movefiles($slugger,$uploadedFiles,$accident));


            $accidentRepository->save($accident, true);

            return $this->redirectToRoute('app_accident_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('accident/edit.html.twig', [
            'accident' => $accident,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit2', name: 'app_accident_edit2', methods: ['GET', 'POST'])]
    public function edit2($id,Request $request, Accident $accident, AccidentRepository $accidentRepository,SluggerInterface $slugger): Response
    {
        $form = $this->createForm(AccidentType::class, $accident);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $uploadedFiles = $form->get('image')->getData();
            $accident->setImage($this->movefiles($slugger,$uploadedFiles,$accident));


            $uploadedFiles = $form->get('image_voiture_reparee')->getData();
            $accident->setImageVoitureReparee($this->movefiles($slugger,$uploadedFiles,$accident));



            $uploadedFiles = $form->get('image_piece_endommage')->getData();
            $accident->setImagePieceEndommage($this->movefiles($slugger,$uploadedFiles,$accident));



            $uploadedFiles = $form->get('image_nouveau_pieces')->getData();
            $accident->setImageNouveauPieces($this->movefiles($slugger,$uploadedFiles,$accident));

            $uploadedFiles = $form->get('image_facture_reparation')->getData();
            $accident->setImageFactureReparation($this->movefiles($slugger,$uploadedFiles,$accident));


            $accidentRepository->save($accident, true);

            return $this->redirectToRoute('app_accident_show', ['id'=>$id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('accident/edit.html.twig', [
            'accident' => $accident,
            'form' => $form,
        ]);
    }






    #[Route('/{id}', name: 'app_accident_delete', methods: ['POST'])]
    public function delete(Request $request, Accident $accident, AccidentRepository $accidentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$accident->getId(), $request->request->get('_token'))) {
            $accidentRepository->remove($accident, true);
        }

        return $this->redirectToRoute('app_accident_index', [], Response::HTTP_SEE_OTHER);
    }

//, methods: ['POST']
    #[Route('/{id}/{image}', name: 'app_image_delete', methods: ['GET'])]
    function deleteImage(int $image ,int $id, EntityManagerInterface $entityManager): Response
    {
        $accident = $entityManager->getRepository(Accident::class)->find($id);
        $imagePath = "/uploads/personne/";
        if ($accident){
            switch ($image){
                case 0:
                    $imagePath = $imagePath.$accident->getImage();

                    $accident->setImage(null);
                    break;
            }
            switch ($image){
                case 1:
                    $imagePath = $imagePath.$accident->getImageVoitureReparee();

                    $accident->setImageVoitureReparee(null);

templates/accident/_form.html.twig
{{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
<div class="form-group">
    {{ form_row(form. nom_client, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.prenom_client, {'attr': {'class': 'form-control'}}) }}

    {{ form_row(form.matricule, {'attr': {'class': 'form-control'}}) }}


        {{ form_row(form.image, {'attr': {'class': 'form-control'}}) }}

    {{ form_row(form.image_voiture_reparee, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.image_piece_endommage, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.image_nouveau_pieces, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.image_facture_reparation, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.lieu_mecaniciens, {'attr': {'class': 'form-control'}}) }}


</div>


<button class="btn {{ button_color|default('btn-outline-primary') }}  mt-3">{{ button_label|default('sauvgarder') }}</button>


{{ form_end(form) }}

templates/accident/edit.html.twig
{% extends 'baseback.html.twig' %}

{% block title %}Edit Accident{% endblock %}


{% block body %}
    <style>
        .container{
            max-width: 60%;
            margin-top: 5%;
        }
    </style>

    <div class="container">
        <h2 class="text-center mt-5 mb-3">Modifier voiture accident</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_accident_index') }}">
                    voir tout les Voitures
                </a>
            </div>
            <div class="card-body">
                {% include 'accident/_form.html.twig' with {'button_label': 'Update voiture accidentee', 'button_color': 'btn-outline-success'}  %}
            </div>
        </div>
    </div>
{% endblock %}

templates/accident/form.html.twig
form_start{{ form(form) }}

templates/accident/index.html.twig
{% extends 'baseback.html.twig' %}

{% block title %}les voitures accidentees {% endblock %}

{% block body %}
    <style>
        .container{
            max-width: 60%;
            margin-top: 5%;
        }
    </style>
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Liste des Voitures accidentées</h2>
        <div class="card">
           <!-- <div class="card-header">
                <a class="btn btn-outline-primary" href="{{ path('app_accident_new') }}">
                    creer nouvelle voiture accidentee
                </a> -->
            </div>

            <div class="card-body">
                <table class="table table-bordered">

                    <tr>
                        <th>Id</th>
                        <th>Nom_client</th>
                        <th>Prenom_client</th>
                        <th>Matricule</th>
                        <th>Image_voiture</th>
                        <th>Image_voiture_reparee</th>
                        <th>Image_piece_endommage</th>
                        <th>Image_nouveau_pieces</th>
                        <th>Image_facture_reparation</th>
                        <th>actions</th>


                    </tr>
                    {% for accident in accidents %}
                        <tr>
                            <td>{{ accident.id }}</td>
                            <td>{{ accident.nomClient }}</td>
                            <td>{{ accident.prenomClient }}</td>
                            <td>{{ accident.matricule }}</td>
                            <td>{{ accident.image }}</td>
                            <td>{{ accident.imageVoitureReparee }}</td>
                            <td>{{ accident.imagePieceEndommage }}</td>
                            <td>{{ accident.imageNouveauPieces }}</td>
                            <td>{{ accident.imageFactureReparation }}</td>

                            <td>
                                <form method="post" action="{{ path('app_accident_delete', {'id': accident.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                    <a
                                            class="btn btn-outline-info"
                                            href="{{ path('app_accident_show', {'id': accident.id}) }}">
                                        Show
                                    </a>
                                    <a
                                            class="btn btn-outline-success"
                                            href="{{ path('app_accident_edit', {'id': accident.id}) }}">
                                        Edit
                                    </a>

                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ accident.id) }}">
                                    <button class="btn btn-outline-danger">Delete</button>

                                </form>
                            </td>

                        </tr>
                    {% endfor %}
                </table>
                <div class="count">
                    {{ knp_pagination_render(accidents) }}
                </div>
            </div>
        </div>

    </div>

{% endblock %}

templates/accident/map.html.twig
{% extends '../base.html.twig' %}
{% block body %}
    <h1 style="margin-top: 60px ;color:saddlebrown;margin-left:50px">Carte Maps</h1>
    <div style="width: 100%; height: 500px;">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d319190.19126167454!2d10.111007428027984!3d34.79768609073896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12f5865de0a44a57%3A0x5aa5c79169806ef0!2sTunisie!5e0!3m2!1sfr!2stn!4v1646814821733!5m2!1sfr!2stn"
                width="100%" height="100%" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
        </iframe>
    </div>
{% endblock %}


<a href="{{ path('map') }}">
    <button class="btn btn-info">Consulter Map</button>

templates/accident/new.html.twig
{% extends 'base.html.twig' %}



{% block title %}Ajouter Voiture Accidentee{% endblock %}

{% block body %}
    <style>
        .container{
            max-width: 75%;
            margin-top: 5%;
        }
    </style>
    <div class="container"  >
        <h2 class="text-center mt-5 mb-3">Deposer les photos de la  voiture accidentee</h2>
        <div class="card">
         <!--   <div class="card-header">
                <a class="btn btn-outline-info float-right" href="">
                    notifier client
                </a>
            </div> -->

            <div class="card-body">

                {{ include('accident/_form.html.twig') }}

                </form>
            </div>


        </div>
    </div>
    <div>
    <h1 style="margin-top: 60px ;color:saddlebrown;margin-left:50px">Carte Maps:</h1>
        <style>
            .map{
              display: flex;
                position: center;
                margin-left: 20%;
                margin-bottom: 200%;
            }
        </style>

    <div class="map" style="width: 70%; height: 500px; margin-right: 80%; display: flex;position: center">

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d319190.19126167454!2d10.111007428027984!3d34.79768609073896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12f5865de0a44a57%3A0x5aa5c79169806ef0!2sTunisie!5e0!3m2!1sfr!2stn!4v1646814821733!5m2!1sfr!2stn"
                width="100%" height="150%" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
        </iframe>
    </div>
    </div>




{% endblock %}

templates/accident/show.html.twig
{% extends 'baseback.html.twig' %}

{% block title %}Afficher voiture accidentee {{ accident.id }}{% endblock %}

{% block body %}

    <style>
        .container{
            max-width: 75%;
            margin-top: 5%;
        }
    </style>
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Voitures accidentees de {{ accident.nomclient }}  {{ accident.prenomclient }}
         Matricule :{{ accident.matricule }}</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_accident_index') }}">
                    voir tout les voitures
                </a>
            </div>
            <div class="card-body">

                <table>
                    <td width="500px">
                <b class="text-muted">Nom:</b>
                <p>{{ accident.nomclient }}</p>
                <b class="text-muted">Prenom:</b>
                <p>{{ accident.prenomclient }}</p>
                <b class="text-muted">Matricule:</b>
                <p>{{ accident.matricule }}</p>


                    <td width="700px">
                        <div>
                <b class="text-muted">Image_voiture_etat_accidente:</b>
                            {% set filePaths = accident.image|split(',') %}
                            {% for filePath in filePaths %}
                                <p>    <img src="{{ asset('uploads/personne/' ~ filePath) }}"  width="100%"></p>
                                <a href="{{ path('app_image_delete',{id:accident.id,image:0}) }}">Supprimer</a>
                                <a href="{{ path('app_accident_edit2',{id:accident.id}) }}">Modifier</a>


                            {% endfor %}
                <!--<p><img src="" alt="image" width="100%"></p>
                        --></div>
                        <div>
                        <b class="text-muted">Voiture apres la reparation:</b>
                        {% set filePaths = accident.imagevoiturereparee|split(',') %}
                        {% for filePath in filePaths %}
                            <p>
                                <img src="{{ asset('uploads/personne/' ~ filePath) }}"  width="100%"></p>
                            <a href="{{ path('app_image_delete',{id:accident.id,image:1}) }}">Supprimer</a>
                        {% endfor %}
                        </div>

                        <div>
                            <b class="text-muted">Piece Endommage par l'accident:</b>
                            {% set filePaths = accident.imagepieceendommage|split(',') %}
                            {% for filePath in filePaths %}
                                <p>    <img src="{{ asset('uploads/personne/' ~ filePath) }}" width="100%">
                                <a href="{{ path('app_image_delete',{id:accident.id,image:2}) }}">Supprimer</a>
                                </p>
                            {% endfor %}
                        </div>

                        <div>
                            <b class="text-muted">Nouveaux Pieces :</b>
                            {% set filePaths = accident.imagenouveaupieces|split(',') %}
                            {% for filePath in filePaths %}
                                <p>    <img src="{{ asset('uploads/personne/' ~ filePath) }}" width="100%"></p>
                                <a href="{{ path('app_image_delete',{id:accident.id,image:3}) }}">Supprimer</a>
                            {% endfor %}
                        </div>

                        <div>
                            <b class="text-muted">Facture de reparation:</b>
                            {% set filePaths = accident.imagefacturereparation|split(',') %}
                            {% for filePath in filePaths %}

                                <p>    <img src="{{ asset('uploads/personne/' ~ filePath) }}"  width="100%"></p>
                                <a href="{{ path('app_image_delete',{id:accident.id,image:4}) }}">Supprimer</a>
                            {% endfor %}
                        </div>
                </td>
                </table>



            </div>
        </div>
    </div>
{% endblock %}